### PR TITLE
Compliment the Javadoc so build succeeds.

### PR DESCRIPTION
**Pull request by noordawod**
I fulfilled minor Javadoc requirements so the build task succeeds.

### CODE REVIEW

**Comment by j256** [comment]
What system is stopping the building because of javadocs?  I really don't like javadocs which just clutter the code and document stuff which is obvious.

**Comment by noordawod** [comment]
NetBeans.

**Comment by j256** [comment]
Sorry but I'm not going to take this sort of merge.  Can you disable it for this project?

**Comment by noordawod** [comment]
Sure thing, I'll manage on this one on my own. No worries.

**Comment by noordawod** [comment]
I got to the bottom of this, sent a new pull #12.

**Pull request closed without merging**
